### ISSUE TITLE
Value Error in cmd

### ISSUE THREAD

**Issue by nanz17** [SouravJohar/handy#2]
![screenshot 21](https://user-images.githubusercontent.com/38329721/53981679-7fccb780-412c-11e9-841a-a3079c14f02f.png)
This keeps showing up. I tried different hand positions but it didnt work.

**Comment by dhirenpamnani** [comment]
> ![screenshot 21](https://user-images.githubusercontent.com/38329721/53981679-7fccb780-412c-11e9-841a-a3079c14f02f.png)
> This keeps showing up. I tried different hand positions but it didnt work.

Yes same ... please reply if someone found a solution to this issue.

**Comment by dhirenpamnani** [comment]
> ![screenshot 21](https://user-images.githubusercontent.com/38329721/53981679-7fccb780-412c-11e9-841a-a3079c14f02f.png)
> This keeps showing up. I tried different hand positions but it didnt work.

Remove the ' _, 'or ' image, '   in the  line of contours object looking like this  _, contours,

Refer to https://github.com/facebookresearch/maskrcnn-benchmark/issues/339 for solution

**Comment by SouravJohar** [comment]
Fixed this in the latest commit.
